version: '3.9'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    container_name: gw-keycloak
    command: start-dev
    ports:
      - "7251:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password#123


  openresty:
    depends_on:
      - keycloak
    build: ./nginx
    container_name: gw-openresty
    ports: 
      - "7252:80"
    volumes:
      - ./.data/root:/root

  testapp:
    build: testapp
    container_name: gw-testapp
    environment:
      - ACCESS_TOKEN_KEY=fzaccesstoken
      - ACCESS_TOKEN_VALUE=fzaccesstokenvalue
    volumes:
      - ./.data/root:/root
      - ./testapp/app:/app
    ports:
      - "7253:80"






#----------------------------------
  keycloak-old:
    build: ./keycloak
    container_name: gw-keycloak
    ports:
      - "7251:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password#123
    profiles:
      - deprecated