version: '3.9'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "7223:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password#123

  nginx:
    depends_on:
      - keycloak
    build: ./nginx
    container_name: scratch
    ports: 
      - "7222:80"
    volumes:
      - ./.data/root:/root

  testapp:
    build: testapp
    container_name: testapp
    environment:
      - ACCESS_TOKEN_KEY=fzaccesstoken
      - ACCESS_TOKEN_VALUE=fzaccesstokenvalue
    volumes:
      - ./.data/root:/root
      - ./testapp/app:/app
    ports:
      - "7221:80"
